// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace plant_app_backend.Models;

public partial class CUsersJUSTENEDocumentsCoursMSPR61plant_app_backendDBplantappdbContext : DbContext
{
    public CUsersJUSTENEDocumentsCoursMSPR61plant_app_backendDBplantappdbContext(DbContextOptions<CUsersJUSTENEDocumentsCoursMSPR61plant_app_backendDBplantappdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Annonce> Annonces { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Annonce>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_Annonces_UserId");

            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.Photos).IsRequired();
            entity.Property(e => e.Titre).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.Annonces).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.Email).IsRequired();
            entity.Property(e => e.Nom).IsRequired();
            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.Prenom).IsRequired();
            entity.Property(e => e.Pseudo).IsRequired();
            entity.Property(e => e.Sexe).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}